/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  channels: () => import("@/views/channels/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "portal-login": () => import("@/views/portal-login/index.vue"),
  portal_batch: () => import("@/views/portal/batch/index.vue"),
  portal_events: () => import("@/views/portal/events/index.vue"),
  portal: () => import("@/views/portal/index.vue"),
  portal_orders: () => import("@/views/portal/orders/index.vue"),
  portal_overview: () => import("@/views/portal/overview/index.vue"),
  portal_products: () => import("@/views/portal/products/index.vue"),
  portal_recharges: () => import("@/views/portal/recharges/index.vue"),
  portal_single: () => import("@/views/portal/single/index.vue"),
  suppliers: () => import("@/views/suppliers/index.vue"),
};
