/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'channels',
    path: '/channels',
    component: 'layout.base$view.channels',
    meta: {
      title: '渠道管理',
      icon: 'mdi:account-network-outline',
      order: 2,
      i18nKey: 'route.channels',
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'portal',
    path: '/portal',
    component: 'layout.base' as any,
    meta: {
      title: '渠道门户',
      constant: true,
      icon: 'mdi:storefront-outline',
      order: 1,
      i18nKey: 'route.portal'
    },
    children: [
      {
        name: 'portal_batch',
        path: '/portal/batch',
        component: 'view.portal_batch',
        meta: {
          title: '批量充值',
          constant: true,
          order: 3,
          i18nKey: 'route.portal_batch'
        }
      },
      {
        name: 'portal_events',
        path: '/portal/events',
        component: 'view.portal_events',
        meta: {
          title: '消费日志',
          constant: true,
          order: 6,
          i18nKey: 'route.portal_events'
        }
      },
      {
        name: 'portal_orders',
        path: '/portal/orders',
        component: 'view.portal_orders',
        meta: {
          title: '消费记录',
          constant: true,
          order: 5,
          i18nKey: 'route.portal_orders'
        }
      },
      {
        name: 'portal_overview',
        path: '/portal/overview',
        component: 'view.portal_overview',
        meta: {
          title: '概览',
          constant: true,
          order: 1,
          i18nKey: 'route.portal_overview'
        }
      },
      {
        name: 'portal_products',
        path: '/portal/products',
        component: 'view.portal_products',
        meta: {
          title: '商品列表',
          constant: true,
          order: 4,
          i18nKey: 'route.portal_products'
        }
      },
      {
        name: 'portal_recharges',
        path: '/portal/recharges',
        component: 'view.portal_recharges',
        meta: {
          title: '充值日志',
          constant: true,
          order: 7,
          i18nKey: 'route.portal_recharges'
        }
      },
      {
        name: 'portal_single',
        path: '/portal/single',
        component: 'view.portal_single',
        meta: {
          title: '单笔充值',
          constant: true,
          order: 2,
          i18nKey: 'route.portal_single'
        }
      }
    ]
  } as any,
  {
    name: 'portal-login',
    path: '/portal-login',
    component: 'layout.blank$view.portal-login',
    meta: {
      title: '渠道登录',
      constant: true,
      hideInMenu: true,
      i18nKey: 'route.portal-login'
    }
  },
  {
    name: 'suppliers',
    path: '/suppliers',
    component: 'layout.base$view.suppliers',
    meta: {
      title: '供应商管理',
      icon: 'mdi:truck-delivery-outline',
      order: 3,
      i18nKey: 'route.suppliers',
      hideInMenu: true
    }
  }
];
